# Generated by Django 5.2.4 on 2025-07-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0002_alter_bid_id_alter_player_id_alter_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="batting_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="player",
            name="economy",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="player",
            name="matches",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="strike_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="player",
            name="base_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="sold_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
